# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Post

# Model Form Field configuration
form: $/kloos/notify/models/post/fields.yaml

# Model Class name
modelClass: Kloos\Notify\Models\Post

# Default redirect location
defaultRedirect: kloos/notify/posts

# Create page
create:
    title: Create Post
    redirect: kloos/notify/posts/update/:id
    redirectClose: kloos/notify/posts

# Update page
update:
    title: Edit Post
    redirect: kloos/notify/posts
    redirectClose: kloos/notify/posts

# Preview page
preview:
    title: Preview Post
